### ISSUE TITLE
Hassbian Wishlist

### ISSUE THREAD

**Issue by Landrash** [home-assistant/hassbian-scripts#33]
Wish list for functionality that we want to add to Hassbian. Pull requests welcome.

### Install scripts
- [ ] Refactor database scripts for client and server parts.
- [ ] Node-RED
- [ ] Wireguard VPN
- [x] HomeBridge.  **Implemented in #79** 
- [x] Let's Encrypt.  Registration and renewal. **Implemented in #81** 
- [x] ~~MySQL~~. Replaced with MariaDB. **Implemented in #53**
- [x] [AppDaemon](https://community.home-assistant.io/t/setting-up-appdaemon-service-on-hasbian-issues/21683). **Implemented in #52**

### Other functionality
- [x] Iptables. Only listen to specified ports. Add exceptions with install scripts for use with Iptables. 
- [ ]  ~~IPV6 support. Adapt scripts to display ipv6 address if available. Currently not implementable due to upstream problems with only running image with ipv6.~~
- [x] MOTD. Using update-motd. #201 
- [ ] Hotspot if no network functionality is detected. See #8 for details.
- [x] Aliases for commonly used functions, **Implemented in #107**
- [x] Service control functionality for `homeassistant` user.
- [x]  ~~Power profile for wlan0 to off. Not implemented since package can be used with different hardware where this is not applicable.~~

### Additions to base image
- [x] Add zip package
- [ ] Backup and restore
- [x] Load config on first boot

### Extended functionality of scripts
- [x] ~~Add functionality for building Z-wave for older pies with limited amount of memory.~~ Deprecated since package isn't built from source anymore.
- [x] Add compatibility for scripts that doesn't work with Raspberry Pi zero.

**Comment by arsaboo** [comment]
Let's Encrypt registration and renewal please :pray:

**Comment by arsaboo** [comment]
Here are couple more that would be nice to have:
1. MySQLdb
2. Github backup/restore

**Comment by Landrash** [comment]
First one I'm unsure about what it is?

**Comment by arsaboo** [comment]
Instead of using SQLAlchemy, use MySQLdb for the recorder - https://home-assistant.io/components/recorder/

**Comment by Landrash** [comment]
Ahh. The lack of space between MYSQL & db confused me ;)

**Comment by penright** [comment]
Thank @Landrash for adding the AppDaemon to the list.
One other Hassbain install that I had to fight through was Open Zwave barrier fixed.
This link starts where I was adding a Linear garage door opener.
[https://community.home-assistant.io/t/linear-ngdz00-4-garage-door/2136/220?u=penright](url)

There was a lot of patches, that most of them I hope will be in the next Hass release.
But there was some patches to the OZW, not sure I fully understand it right now. I kind of did the monkey thing and got it working. The most relevant part to this discussion is when I asked about future patches and this was the question and the answer given.
![image](https://user-images.githubusercontent.com/21042538/28420860-15b7b38c-6d29-11e7-949f-dd40529ecf3e.png)
![image](https://user-images.githubusercontent.com/21042538/28420915-43979f2e-6d29-11e7-88f1-a0232b07d1f6.png)

Here is the direct link [https://community.home-assistant.io/t/linear-ngdz00-4-garage-door/2136/235?u=penright](url)

**Comment by Landrash** [comment]
@penright Problem with  patch like this is that it won't be persistent between updates. If anything it's something that would need to be fixed in HA itself :slightly_smiling_face:

**Comment by Landrash** [comment]
Appdaemon addressed in #52

**Comment by riemers** [comment]
I think its good to have a cheat sheet once you login. That is like your motd. With things like stop ha, start ha. All those shortcuts that make it easier.. perhaps add shortcuts "hastop" "hastart" "haupgrade"i do a lot of restarting (i always have to disable z-wave for instance to test new stuff) because it takes 10+ minutes to finally be ready. Also when i do log in, i want to be directly in .homeassistant folder if possible :)

**Comment by Landrash** [comment]
@riemers 
 - MOTD is on my list but  had forgotten to add it to this one. Adding it
 - Aliases for commonly used commands are on the list already.
 - Having the default location be the `.homeassistant` directory is something I'm not comfortable changing since it makes a change to something that's standard on most *nix installations.

**Comment by ludeeus** [comment]
PR #79 for homebridge is ready :)

**Comment by ardeus-ua** [comment]
Kiosk mode for connected touchscreen to automatically open Home Assistant. Maybe adaptation of https://github.com/guysoft/FullPageOS

**Comment by Landrash** [comment]
@ardeus-ua Out of scope for Hassbian since we don't ship any kind of gui.
Everything is generally done over ssh.

**Comment by ardeus-ua** [comment]
I mean the scripted installation of kiosk mode for rpi to open Home Assistant gui on device startup

**Comment by Landrash** [comment]
Reopening since this issue should not be closed.

**Comment by akubak** [comment]
I'm working on a Webmin installation script for Hassbian right now - could it be added to the wishlist, or should I submit a PR first?

**Comment by riemers** [comment]
A use case for webmin would be nice too, i know you can do a lot with it, but it all depends on your needs. Are there any good examples on what you want  to achieve with it? (not saying its a bad idea, just wondering)

**Comment by akubak** [comment]
@riemers Webmin makes it really easy to do lots of things you would usually use the CLI for via a GUI, so it could be really useful for beginners. I’ve used it myself in the past, and can confirm that it works fine. AFAIK, you can use it to configure programs like samba or systemd if you’re running services installed from sources other than this (hassbian config).

**Comment by Landrash** [comment]
@Antoni-K I don't think it needs to be in the tool.
It's fairly straight forward to install and the instructions are on the webmin download page.
```
wget http://prdownloads.sourceforge.net/webadmin/webmin_1.760_all.deb
apt install webmin_1.760_all.deb
```

The things we added to Hassbian config has been tweaks and tools that are generally used with Home Assistant. There's a point to where we need to keep a balance between functionality and what goals the product is trying to accomplish or well end up creating a new packaging system.

**Comment by akubak** [comment]
@Landrash Oh, sorry, didn't see your comment. I submitted a pull request already but feel free to close it. Also, I might get started on an rsync-based backup & restore utility, if nobody else is already working on one.

**Comment by riemers** [comment]
Rsync can be cronned, same applies to webmin perhaps. If you do make something with rsync, a better place would be to make a description for it like say https://home-assistant.io/docs/ecosystem/backup/backup_usb/ , that way everybody can enjoy your work regardless of the method they used to install hass.

**Comment by akubak** [comment]
Got it. I was thinking of something similar to your USB backup script, but with rsync so it is slightly faster.

**Comment by riemers** [comment]
If you have a proper setup, it will only sync a few text files no? I would see the use case rather that you can sync it to another location. Something the USB cannot do :) perhaps link it with a ionotify tool for instant backup, sky is the limit.

**Comment by akubak** [comment]
Good idea, maybe also cloud integration (other than dropbox). I'll look into it.

**Comment by riemers** [comment]
If you get bored, why not write an installer that asks you how you want your backup and with what options 🥇

**Comment by akubak** [comment]
Will do 👍

**Comment by ferazambuja** [comment]
~Raspberry Pi Desktop~ :)

**Comment by Landrash** [comment]
@ferazambuja No. Out of scope for this project.

**Comment by ferazambuja** [comment]
I’m Mac user and I enjoy using http://netatalk.sourceforge.net instead of samba. 
It’s an AppleShare file server. 
Is just more seamless and your hassbian home/pi shows automatically as another Mac. However the home assistant config folder needs to be added manually. It also handles reboots way better avoiding your Atom editor to screen errors if you have config files open. 

It doesn’t exclude the need of samba. But it’s an idea to try to make Hassbian even more accessible.

**Comment by swetoast** [comment]
motd is simple we can use neofetch for that looks like this once compiled it takes about 268 kb no need for monster bashscripts that checks everything just include the bin and stick the content below into .bashrc

```
clear; neofetch
```

https://github.com/dylanaraps/neofetch

![image](https://user-images.githubusercontent.com/2525304/42271251-282f285c-7f83-11e8-863f-6669e079b65c.png)

![image](https://user-images.githubusercontent.com/2525304/42271408-89757044-7f83-11e8-9341-78aa7a5f28b4.png)

![image](https://user-images.githubusercontent.com/2525304/42275405-77e9d164-7f90-11e8-88dd-f7ed48f4254e.png)

**Comment by schmittx** [comment]
Any chance we could get a script for FFmpeg, ideally with hardware acceleration enabled and compiled?

**Comment by riemers** [comment]
I think the next logical step would be to have the "add-ons" as packages. Most is already like that but then have an option to do it via the GUI, like hassio does it now too. But contain it to one repo only to not get 100's of repository's.. i know i could help out with scripting part but it is the gui part that i have no skills for. Find one of those and i am more then happy to help out on that part too. Imagine a restore which includes the packages you had and it downloads those for you. (might be wanting the world here, but just giving out my thoughts)

p.s. neofetch is nice, but how often do you login into your device? Besides that all the info it shows.. i know since i bought the device. Much rather prefer a motd that does some home assistant checks "Your running version x, while xx is out. Type xx to upgrade" or one of your packages or addons is out of date etc etc.

**Comment by Landrash** [comment]
@ferazambuja 
No way to test since I use a *nix only environment.  Contributions welcome.

@swetoast Neofetch would be great. Minimal custom code from us and that's generally preferred. 

@schmittx I'll add it to the list but nothing I've worked on before.

@riemers Logging into my Hassbian pi, daily generally.
Making packages will require some more changes to the base tools we have written but it can be considered.

**Comment by riemers** [comment]
@Landrash that you log in to your PI daily is logical :-) I don't do that so often, use also visual studio code with the yaml plugin and samba mount.

**Comment by schmittx** [comment]
How about a Python upgrade script to archive/copy the current venv, install Python, create new venv, etc.?

**Comment by ludeeus** [comment]
@schmittx you mean like this https://github.com/home-assistant/hassbian-scripts/blob/dev/package/opt/hassbian/suites/python.sh ?

**Comment by schmittx** [comment]
@ludeeus Ha, I'm an idiot...disregard...

**Comment by ardeus-ua** [comment]
Is this possible to add ffmpeg with hardware decoding to the base image?

**Comment by Landrash** [comment]
@ardeus-ua Is it available as a package then we could add it as a package.

**Comment by nixme** [comment]
[find3](https://www.internalpositioning.com/doc/). I could possibly attempt to do this.

**Comment by Landrash** [comment]
@nixme Give it a go :) What part of it do you want on the pi?

### Cli-scanner
```
echo "Installating dependencies"
apt install wireless-tools net-tools libpcap-dev bluetooth golang
go get -u -v github.com/schollz/find3-cli-scanner
mv $GOPATH/bin/find3-cli-scanner /usr/local/bin
```

Should be the basics of what you need.

**Comment by ardeus-ua** [comment]
> @ardeus-ua Is it available as a package then we could add it as a package.

https://www.johnvansickle.com/ffmpeg/ here are fresh precompiled binaries
`built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libxml2 --enable-libxvid --enable-libzimg`

**Comment by ghost** [comment]
hi
good will be if you add Backup and restore...

**Comment by dasb00ter** [comment]
I would like to make a request for a good reverse proxy. I am finding the install daunting but it is security related so I feel it would be valuable. If a script could get everything installed in the right places I could probably cobble together a how to wiki for it once I get it running myself. I guess Caddy or NGINX would be good candidates with the former I see being utilized in the HASS.IO addons and therefor perhaps more user friendly

**Comment by jurgenweber** [comment]
can i suggest a flag where you can tell the home assistant suite not to restart on upgrade?

**Comment by ludeeus** [comment]
If you want that use pip manually.

**Comment by Landrash** [comment]
https://www.home-assistant.io/blog/2019/10/26/rip-hassbian/
