### ISSUE TITLE
Hassbian Stretch

### ISSUE THREAD

**Issue by ludeeus** [home-assistant/hassbian-scripts#39]
All issues are experienced on the [1.3 WIP.](https://github.com/home-assistant/pi-gen/releases/tag/1.3)

### Known problems ###
- [x] **sudo hassbian-config install mosquitto _failed_**: Missing dependicies (libssl & libwebsockets)
   _Workaround in place in the newest package of hassbian-config_
- [x] **sudo hassbian-config install hue _failed_**: Worng python version, should be 3.5 not 3.4
- [ ] **sudo hassbian-config install libcec _failed_**: Problems with python 3.5 & 3.6. Script should function when fixed in project.
- [ ] ~~**sudo hassbian-config install tellstick _failed_**: libconfuse0 (>= 2.5) but it is not installable~~
- [x] **Unable to install package pyatv==0.3.4**

### Working/Tested ###
- [x] Tradfri
- [x] Samba
- [x] Home-assistant

### To be removed ###
- [x] OpenZwave-pip. Baked in into Home Assistant.
- [x] Tellstick. Packages has not been updated since 2014 and are missing dependencies in Debian Stretch.

### To be added ###
- [x] Upgrades to hassbian-config by @ludeeus in #42 
- [x] Added scripts to upgrade HA by @ludeeus in #42 
- [x] Added scripts to upgrade base OS by @ludeeus in #42 
- [x] Added scripts to upgrade hassbian-config by @ludeeus in #42 
- [x] Permissions for audio recommended by @Ammaddon reference material [here](http://blog.scphillips.com/posts/2013/01/sound-configuration-on-raspberry-pi-with-alsa/).

**Comment by ludeeus** [comment]
Added this #40 for hue.

**Comment by Landrash** [comment]
Libcec script fixed in stretch branch. Problems with python 3.5 & 3.6. Script should function when fixed in project.
Hue fixed in stretch branch and an alternative fix has been submitted by @ludeeus in #40 . Considering implementing that fix since it's a better option.
Openzwave & pyAtv are WIP since some changes are needed to the base system since dependencies has changed.
Mosquitto is almost done but not properly tested.

Tellstick will be removed since packages are not available for Tellstick.

**Comment by Landrash** [comment]
Closing after release

**Comment by hnnweb** [comment]
Tellstick works in Stretch

https://community.home-assistant.io/t/home-assistant-running-on-raspberry-pi-2-b-with-tellstick-duo/4346/12

**Comment by Landrash** [comment]
@hnnweb Feel free to submit a new install script for it. I'll try to do it if not when I got the time but that might take a while.
